### ISSUE TITLE
File name regex is incomplete.

### ISSUE THREAD

**Issue by laasfeld** [Boa-Byte/SpheraSense#11]
The file name regex is currently given as 

`            pattern = '(?<WellID>\w+)_(?<ReadIndex>\d+)_(?<ChannelIndex>\d+)_(?<ZIndex>\w+)_(?<ChannelName>[\w\s]+)_(?<CycleIndex>\d+)';
` 
(in commit 41cd2d3, 'app_one.mlapp', line 57)
but this results in ZIndex matching '1Z0' from 'F2_03_1_1Z0_Bright Field_002.tif'. In reality, the '1' in '1Z0' is the Field of view (FOV) index and 'Z0' is the Z-plane index, so these must be separated either in this regex or further split at 'Z'.

**Comment by Boa-Byte** [comment]
Updated regex,  split ZIndex into WellIndex and ZPlane
